import {StyleSheet} from 'react-native';
 
const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  resultAlt:{
    borderWidth: 1,
    borderStyle: 'dotted',
    borderColor: 'red',
    padding: 5,
    marginTop: 30,
    color: 'red',
  },
  lowWeight: {
    alignSelf: 'center',
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 20,
    borderBottomWidth: 1,
    borderColor: '#FFBA00',
    color: '#FFBA00',
  },
  normalWeight: {
    alignSelf: 'center',
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 20,
    borderBottomWidth: 1,
    borderColor: '#118108',
    color: '#118108',
  },
  overWeight: {
    alignSelf: 'center',
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 20,
    borderBottomWidth: 1,
    borderColor: '#FF0000',
    color: '#FF0000',
  },
  highWeight: {
    alignSelf: 'center',
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 20,
    borderBottomWidth: 1,
    borderColor: '#AC00B7',
    color: '#AC00B7',
  },
  higherWeight: {
    alignSelf: 'center',
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 20,
    borderBottomWidth: 1,
    borderColor: '#540459',
    color: '#540459',
  },
  dangerWeight: {
    alignSelf: 'center',
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 15,
    borderBottomWidth: 1,
    borderColor: '#090808',
    color: '#090808',
  },
});

export {styles};